# Site configuration ----------------------------------------------------------
# Based on a fork of github.com/barryclark/jekyll-now.

name: unnamed  # site name
description: learning to teach machines to learn
avatar: https://raw.githubusercontent.com/alexanderdesouza/alexanderdesouza.github.io/master/images/alexanderdesouzagithubio.jpg

# Optional flags --------------------------------------------------------------

# Include an icon in the footer for each username provided:
footer-links:
#  email: firstname.lastname at google mail punt com
  github: alexanderdesouza
  linkedin: alexander-l-desouza
#  dribble: 
#  facebook: 
#  flickr: 
#  instagram:
#  pinterest: 
#  rss: # type anything here for a working RSS icon
#  twitter: 
#  stackoverflow: # stackoverflow profile, e.g. "users/50476/bart-kiers"
#  youtube: # channel/<your_long_string> or user/<user-name>
#  googleplus: # from your profile username after plus.google.com/

# Provide a disqus shortname to enable commenting on posts:
# disqus: 

# Enter a tracking code (e.g., UA-2110908-2) to activate Google Web Analytics:
# google_analytics:

# Personal website URL:
url: http://alexanderdesouza.github.io

# Additional configuration ----------------------------------------------------

permalink: /:title/
version: v1.2.0  # version of Jekyll Now being used

# Jekyll 3 now supports Kramdown for Markdown:
kramdown:
  input: GFM  # use GitHub flavored markdown, including triple backtick fenced
              # code blocks
  syntax_highlighter: rouge  # for syntax highlighting
  syntax_highlighter_opts: 
    css_class: 'highlight'  # use existing pygments syntax highlighting css

# Sets the Sass partials directory using @imports:
sass:
  style: :compressed

# Use the following plug-ins:
# gems:
#   - jekyll-sitemap  # Create a sitemap using the official Jekyll sitemap gem
#   - jekyll-feed     # Create an Atom feed using the official Jekyll feed gem

# Exclude these files from the production _site
exclude:
  - Gemfile
  - Gemfile.lock
  - LICENSE
  - README.md
  - CNAME
